# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ "/dev/tty2" == $(tty) ]]
then
    startx
fi

export ZSH="/home/anurag/.oh-my-zsh"
export EDITOR="nvim"

ZSH_THEME="powerlevel10k/powerlevel10k"
HIST_STAMPS="dd.mm.yyyy"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting vi-mode)

source $ZSH/oh-my-zsh.sh

alias zrc="nvim ~/.zshrc"
alias rr=". ranger"
alias h="htop"
alias c="clear"
alias q="exit"
alias ls='exa --color=always --group-directories-first --icons'  # all files and dirs
alias la='exa -al --color=always --group-directories-first --icons --git' # my preferred listing
alias ll='exa -l --color=always --group-directories-first --icons --git'  # long format
alias l.='exa -a | rg "^\."'
alias icat='kitty +kitten icat'
alias clip='tr -d "\n" | xclip -selection clipbaord'
alias n='nvim'
alias du='/sbin/du -h'
alias mtp='aft-mtp-mount ~/mnt'
alias ssh='kitty +kitten ssh'
alias mkdwm='rm -rf config.h && sudo make clean install'
alias btdc='bluetoothctl disconnect && bluetoothctl power off'
alias btcn='bluetoothctl power on; bluetoothctl connect 8C:64:A2:2F:E6:99'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$HOME/.platformio/penv/bin:$HOME/bin:/usr/local/bin:/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/home/anurag/.local/bin:/home/anurag/.program:$PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

autoload -Uz compinit
compinit
# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


[[ -s /home/anurag/.autojump/etc/profile.d/autojump.sh ]] && source /home/anurag/.autojump/etc/profile.d/autojump.sh

autoload -U compinit && compinit -u
